Repository khanlab/hippunfold, pull requests merged in 2022-01, with the labels that each got.

#147 Update release-drafter.yml
  .github/release-drafter.yml
Labels: maintenance

#145 root dir change for snakebids 0.4.0
  .github/workflows/python-testing.yml
  docs/getting_started/outputs.rst
  hippunfold/config/snakebids.yml
  hippunfold/tests/hippunfold_test.py
  hippunfold/workflow/Snakefile
  hippunfold/workflow/rules/autotop.smk
  hippunfold/workflow/rules/common.smk
  hippunfold/workflow/rules/gifti.smk
  hippunfold/workflow/rules/nnunet.smk
  hippunfold/workflow/rules/preproc_cropseg.smk
  hippunfold/workflow/rules/preproc_hippb500.smk
  hippunfold/workflow/rules/preproc_seg.smk
  hippunfold/workflow/rules/preproc_t1.smk
  hippunfold/workflow/rules/preproc_t2.smk
  hippunfold/workflow/rules/resample_final_to_crop_t1.smk
  hippunfold/workflow/rules/shape_inject.smk
  hippunfold/workflow/rules/subfields.smk
  hippunfold/workflow/rules/warps.smk
  poetry.lock
  pyproject.toml
  requirements.txt
Labels: enhancement, maintenance, breaking

#148 Auto-formatting and quality-checks
  .github/workflows/python-testing.yml
  hippunfold/download_models.py
  hippunfold/resources/tpl-upenn/Snakefile
  hippunfold/resources/write_config_NiftyNet.py
  hippunfold/run.py
  hippunfold/workflow/Snakefile
  hippunfold/workflow/rules/autotop.smk
  hippunfold/workflow/rules/common.smk
  hippunfold/workflow/rules/gifti.smk
  hippunfold/workflow/rules/nnunet.smk
  hippunfold/workflow/rules/preproc_cropseg.smk
  hippunfold/workflow/rules/preproc_hippb500.smk
  hippunfold/workflow/rules/preproc_seg.smk
  hippunfold/workflow/rules/preproc_t1.smk
  hippunfold/workflow/rules/preproc_t2.smk
  hippunfold/workflow/rules/resample_final_to_crop_t1.smk
  hippunfold/workflow/rules/shape_inject.smk
  hippunfold/workflow/rules/subfields.smk
  hippunfold/workflow/rules/warps.smk
  hippunfold/workflow/scripts/constrain_surf_to_bbox.py
  hippunfold/workflow/scripts/create_warps.py
  hippunfold/workflow/scripts/dice.py
  hippunfold/workflow/scripts/equivolume_coords.py
  hippunfold/workflow/scripts/fillnanvertices.py
  hippunfold/workflow/scripts/gen_volume_tsv.py
  hippunfold/workflow/scripts/label_subfields_from_vol_coords.py
  hippunfold/workflow/scripts/laplace_coords.py
  hippunfold/workflow/scripts/laplace_coords_withinit.py
  hippunfold/workflow/scripts/plot_subj_subfields.py
  hippunfold/workflow/scripts/prep_equivolume_coords.py
  hippunfold/workflow/scripts/resample_unfolded_label.py
  hippunfold/workflow/scripts/vis_qc_dseg.py
  hippunfold/workflow/scripts/vis_qc_surf.py
  hippunfold/workflow/scripts/vis_regqc.py
  pyproject.toml
Labels: maintenance

#150 Docs from RST to Markdown
  README.md
  README.rst
  docs/conf.py
  docs/contributing/contributing.md
  docs/getting_started/installation.md
  docs/getting_started/installation.rst
  docs/getting_started/outputs.md
  docs/getting_started/outputs.rst
  docs/images/hippunfold_overview.jpg
  docs/index.rst
  docs/requirements.txt
  docs/tutorials/specializedScans.md
  docs/tutorials/specializedScans.rst
  docs/tutorials/standardBIDS.md
  docs/tutorials/standardBIDS.rst
  docs/usage/app_cli.md
  docs/usage/app_cli.rst
  docs/usage/snakemake_cli.md
  docs/usage/snakemake_cli.rst
Labels: documentation

#157 quick patch to prevent source config file from being modified
  hippunfold/run.py
Labels: bug

#155 output refactoring, removed datatype=seg folders, added coords, warps
  .github/workflows/python-testing.yml
  docs/images/dentate_cor.png
  docs/tutorials/outputs.md
  hippunfold/config/snakebids.yml
  hippunfold/workflow/Snakefile
  hippunfold/workflow/rules/autotop.smk
  hippunfold/workflow/rules/common.smk
  hippunfold/workflow/rules/gifti.smk
  hippunfold/workflow/rules/nnunet.smk
  hippunfold/workflow/rules/preproc_cropseg.smk
  hippunfold/workflow/rules/preproc_hippb500.smk
  hippunfold/workflow/rules/preproc_seg.smk
  hippunfold/workflow/rules/preproc_t1.smk
  hippunfold/workflow/rules/preproc_t2.smk
  hippunfold/workflow/rules/resample_final_to_crop_native.smk
  hippunfold/workflow/rules/shape_inject.smk
  hippunfold/workflow/rules/subfields.smk
  hippunfold/workflow/rules/warps.smk
Labels: maintenance

#159 allowing qc to use corobl
  .dryrun_test_all.sh
  hippunfold/workflow/Snakefile
  hippunfold/workflow/rules/common.smk
  hippunfold/workflow/rules/qc.smk
  hippunfold/workflow/rules/resample_final_to_crop_native.smk
  hippunfold/workflow/rules/subfields.smk
Labels: bug

#160 added logging
  hippunfold/workflow/rules/autotop.smk
  hippunfold/workflow/rules/common.smk
  hippunfold/workflow/rules/gifti.smk
  hippunfold/workflow/rules/nnunet.smk
  hippunfold/workflow/rules/preproc_t1.smk
  hippunfold/workflow/rules/preproc_t2.smk
  hippunfold/workflow/rules/qc.smk
  hippunfold/workflow/rules/shape_inject.smk
  hippunfold/workflow/rules/warps.smk
  hippunfold/workflow/scripts/constrain_surf_to_bbox.py
  hippunfold/workflow/scripts/equivolume_coords.py
  hippunfold/workflow/scripts/resample_unfolded_label.py
Labels: maintenance

#163 replace pypi badge with github version tag
  README.md
Labels: documentation
