Repository khanlab/hippunfold, pull requests merged in 2022-09, with the labels that each got.

#210 added --version to CLI (via snakebids.yml)
  .bumpversion.cfg
  .github/workflows/bump_version.yml
  hippunfold/config/snakebids.yml
  hippunfold/pipeline_description.json
Labels: enhancement

#211 bugfix: subfields label.gii wasn't being generated properly
  hippunfold/workflow/rules/gifti.smk
Labels: bug

#213 updated deploy workflow with bumpversion changes
  .github/workflows/deploy.yml
Labels: maintenance

#216 Added missing container for hippdwi_to_template
  hippunfold/workflow/rules/preproc_hippb500.smk
Labels: bug
