Repository khanlab/hippunfold, pull requests merged in 2023-07, with the labels that each got.

#242 curvature was producing a few outlier extreme values
  hippunfold/workflow/rules/gifti.smk
  hippunfold/workflow/scripts/normalize_tanh.py
Labels: bug

#244 Synthseg model
  .github/workflows/push_container.yml
  README.md
  hippunfold/config/nnunet_model_urls.yml
  hippunfold/config/snakebids.yml
  hippunfold/download_models.py
  hippunfold/workflow/rules/autotop.smk
  hippunfold/workflow/rules/nnunet.smk
  hippunfold/workflow/rules/preproc_hippb500.smk
  hippunfold/workflow/rules/qc.smk
  hippunfold/workflow/rules/shape_inject.smk
Labels: enhancement

#228 Unfold reg
  .github/workflows/push_container.yml
  Dockerfile
  README.md
  docs/.gitignore
  docs/images/hippunfold_overview_unfoldreg.png
  docs/images/pipeline_overview_bigbrain.png
  hippunfold/config/nnunet_model_urls.yml
  hippunfold/config/snakebids.yml
  hippunfold/download_models.py
  hippunfold/resources/desc-subfields_atlas-histologyReference2023_dseg.tsv
  hippunfold/resources/histologyReference2023/curvature.nii.gz
  hippunfold/resources/histologyReference2023/gyrification.nii.gz
  hippunfold/resources/histologyReference2023/labellist.txt
  hippunfold/resources/histologyReference2023/snaplabels.txt
  hippunfold/resources/histologyReference2023/sub-maxprob_label-hipp_desc-manualsubfieldsunfoldaligned_dseg.nii.gz
  hippunfold/resources/histologyReference2023/thickness.nii.gz
  hippunfold/resources/histologyReference2023/unfolded2Dref.nii.gz
  hippunfold/workflow/Snakefile
  hippunfold/workflow/rules/autotop.smk
  hippunfold/workflow/rules/gifti.smk
  hippunfold/workflow/rules/nnunet.smk
  hippunfold/workflow/rules/preproc_hippb500.smk
  hippunfold/workflow/rules/preproc_t1.smk
  hippunfold/workflow/rules/qc.smk
  hippunfold/workflow/rules/shape_inject.smk
  hippunfold/workflow/rules/subfields.smk
  hippunfold/workflow/rules/warps.smk
  hippunfold/workflow/scripts/create_warps.py
  hippunfold/workflow/scripts/expand_2Dwarp.py
  hippunfold/workflow/scripts/label_subfields_from_vol_coords.py
  hippunfold/workflow/scripts/normalize_tanh.py
  hippunfold/workflow/scripts/warp_flatsurf.py
Labels: major

#246 Update README.md
  README.md
Labels: documentation
